# Broken App Issues

- err in the next(err) in the catch statement is not defined. There is no error handler function.
